### ISSUE TITLE
CurseBreaker is back

### ISSUE THREAD

**Issue by AcidWeb** [ogri-la/wowman-comrades#33]
Support for CurseForge and Yak was removed.
Support for Wago Addons was added.

**Comment by torkus** [comment]
Welcome back! I think a lot of people really missed CurseBreaker

**Comment by AcidWeb** [comment]
Sadly lot of them only loved it because it supported CurseForge :-P

**Comment by torkus** [comment]
I sympathise. I scrutinised my own motivations after the Curseforge/Overwolf announcement and concluded it can't be the love and support of my users that keeps me developing Strongbox because I get almost zero feedback and have no clue how many are using it. I take it a little less seriously now and dropping Curseforge was just another problem I enjoyed solving :)

I probably won't be adding Wago support, they have an Overwolf vibe, but there is a lot of love for Github these days. @layday is maintaining a Github catalogue you might find interesting: https://github.com/layday/github-wow-addon-catalogue

**Comment by torkus** [comment]
All updated.

**Comment by AcidWeb** [comment]
Yeah. Seen that catalogue.

OW clusterfuck really caused generic users to search for alternative addon sources. I personally have very good relation with Wago Addons. They want to talk - and you can't say they same about OW and their "new" anti-consumer API.
